spring.profiles.include: secret

# TODO: Set AWS S3 info
#cloud:
#  aws:
#    stack:
#      auto: false

spring:
  mvc: # for swagger-ui
    pathmatch:
      matching-strategy: ant_path_matcher

auth.jwt:
  jwtSecret: thisisourtoyprojectappdlqslek148190
  issuer: team2.wafflestudio.com
  jwtAccessExpiration: 300
  jwtRefreshExpiration: 1209600
---
spring.config.activate.on_profile: dev
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/jisik2n?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Seoul
    username: team2
    password: jisik2n
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update

---
spring.config.activate.on_profile: prod
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${rds.hostname}:${rds.port}/${rds.dbname}?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Seoul
    username: ${rds.username}
    password: ${rds.password}
  jpa:
    show-sql: false
    generate-ddl: true
    hibernate:
      ddl-auto: create
server:
  port:
    5000