# Secret properties (example: rds server url, aws endpoint, aws s3 api) will be placed here.
# S3
cloud:
  aws:
    credentials:
      access-key: adf
      bucket-name:
    region:
      static: ap-northeast-2
auth.jwt:
  jwtSecret: asdf
  issuer:
  jwtAccessExpiration: 300
  jwtRefreshExpiration: 1209600