spring.profiles.include: secret

spring:
  mvc: # for swagger-ui
    pathmatch:
      matching-strategy: ant_path_matcher
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 100MB

cloud:
  aws:
    stack:
      auto: false
    s3:
      dir: images

---
spring.config.activate.on_profile: dev

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/jisik2n?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Seoul
    username: team2
    password: jisik2n
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update

---
spring.config.activate.on_profile: prod
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${rds.hostname}:${rds.port}/${rds.dbname}?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Seoul
    username: ${rds.username}
    password: ${rds.password}
  jpa:
    show-sql: false
    generate-ddl: true
    hibernate:
      ddl-auto: create
server:
  port:
    5000

auth.jwt:
  jwtSecret: ${jwt.secret}
  issuer: ${jwt.issuer}
  jwtAccessExpiration: ${jwt.access.expiration}
  jwtRefreshExpiration: ${jwt.refresh.expiration}

cloud:
  aws:
    credentials:
      access-key: ${aws.access.key.id}
      secret-key: ${aws.secret.access.key}
    s3:
      bucket-name: ${aws.bucket}
    region:
      static: ${aws.region}
