# Secret properties (example: rds server url, aws endpoint, aws s3 api) will be placed here.
# S3
cloud:
  aws:
    credentials:
      access-key: AKIAY2A3GFDVE74NI63W
      secret-key: x74yvXVmnKoJYq0tcgSm+wOTjToMKGBkj8+dMq+e
    s3:
      bucket-name: elasticbeanstalk-ap-northeast-2-605647415530
    region:
      static: ap-northeast-2
auth.jwt:
  jwtSecret: myfavoritewaffleischocolatewafflejisik2n
  issuer: team2.wafflestudio.com
  jwtAccessExpiration: 300
  jwtRefreshExpiration: 1209600